# Generated by Django 5.1.7 on 2025-04-23 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_design'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Design',
        ),
    ]
